# Generated by Django 5.1.4 on 2025-02-20 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=100)),
                ('game_link', models.URLField(help_text='Enter the URL where the game is hosted')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_games', to='patients.patientinformation')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='games.game')),
            ],
        ),
    ]
