# Generated by Django 5.1.4 on 2025-01-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=100)),
                ('game_link', models.URLField(help_text='Enter the URL where the game is hosted')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='games/thumbnails/')),
            ],
        ),
    ]
