# Generated by Django 5.1.4 on 2025-01-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='free_to_play',
        ),
        migrations.AddField(
            model_name='game',
            name='game_link',
            field=models.URLField(default='https://example.com', help_text='Enter the URL where the game is hosted'),
            preserve_default=False,
        ),
    ]
