# Generated by Django 5.1.2 on 2025-02-15 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedgame',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_games', to='patients.patientinformation'),
        ),
        migrations.AddField(
            model_name='assignedgame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='games.game'),
        ),
    ]
