# Generated by Django 5.1.4 on 2025-02-11 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('patients', '0003_remove_patientinformation_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='games.game')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_games', to='patients.patientinformation')),
            ],
        ),
    ]
