# Generated by Django 5.1.1 on 2025-01-10 14:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639123456789' or '09123456789'.", regex='^(\\+63|0)9\\d{9}$')])),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assistant Information',
                'verbose_name_plural': 'Assistant Information',
            },
        ),
        migrations.CreateModel(
            name='GuardianInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639123456789' or '09123456789'.", regex='^(\\+63|0)9\\d{9}$')])),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('relationship_to_patient', models.CharField(blank=True, max_length=50, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guardian Information',
                'verbose_name_plural': 'Guardian Information',
            },
        ),
        migrations.CreateModel(
            name='TherapistInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639123456789' or '09123456789'.", regex='^(\\+63|0)9\\d{9}$')])),
                ('city', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Therapist Information',
                'verbose_name_plural': 'Therapist Information',
            },
        ),
    ]
