# Generated by Django 5.1.1 on 2025-02-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardianinformation',
            name='relationship_to_patient',
        ),
    ]
