# Generated by Django 5.1.2 on 2025-02-19 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantinformation',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='guardianinformation',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='therapistinformation',
            name='religion',
        ),
    ]
