# Generated by Django 5.1.4 on 2025-02-20 13:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=50)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientinformation')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to='accounts.therapistinformation')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639123456789' or '09123456789'.", regex='^(\\+63|0)9\\d{9}$')])),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('original_date', models.DateField(blank=True, null=True)),
                ('original_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=50)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='accounts.therapistinformation')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('recurrence_pattern', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('bi-weekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=50)),
                ('number_of_occurrences', models.PositiveIntegerField(default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_appointments', to='patients.patientinformation')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_recurring_appointments', to='accounts.therapistinformation')),
            ],
        ),
    ]
