# Generated by Django 5.1.2 on 2025-01-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_patient_94a7ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_therapi_9ea39e_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_date_85c852_idx',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='recurringappointment',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=50),
        ),
    ]
