# Generated by Django 5.1.2 on 2025-02-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='original_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
