# Generated by Django 5.1.2 on 2025-01-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringappointment',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='recurringappointment',
            name='appointment_patient_ea23ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='recurringappointment',
            name='appointment_therapi_2a0273_idx',
        ),
        migrations.RemoveField(
            model_name='recurringappointment',
            name='end_date',
        ),
        migrations.AddField(
            model_name='recurringappointment',
            name='number_of_occurrences',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
