# Generated by Django 5.1.2 on 2025-02-09 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_id_alter_appointmentrequest_id_and_more'),
        ('patients', '0002_patientinformation_relationship_to_guardian'),
        ('therapists', '0004_availableslot_delete_availableday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonworkingday',
            name='therapist',
        ),
        migrations.AddField(
            model_name='appointment',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientinformation'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='patients.patientinformation'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_requests', to='therapists.therapist'),
        ),
        migrations.DeleteModel(
            name='AppointmentSlot',
        ),
        migrations.DeleteModel(
            name='NonWorkingDay',
        ),
    ]
