# Generated by Django 5.1.2 on 2025-02-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_remove_nonworkingday_therapist_appointment_guardian_and_more'),
        ('patients', '0002_patientinformation_relationship_to_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='patient',
        ),
        migrations.AlterField(
            model_name='recurringappointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_appointments', to='patients.patientinformation'),
        ),
    ]
