# Generated by Django 5.1.2 on 2025-02-09 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointmentrequest_guardian_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentrequest',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
