# Generated by Django 5.1.2 on 2025-02-12 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_guardianinformation_relationship_to_patient'),
        ('appointments', '0007_alter_appointment_patient'),
        ('patients', '0002_patientinformation_relationship_to_guardian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to='accounts.therapistinformation'),
        ),
        migrations.AlterField(
            model_name='appointmentrequest',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='accounts.therapistinformation'),
        ),
        migrations.AlterField(
            model_name='recurringappointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_appointments', to='patients.patientinformation'),
        ),
        migrations.AlterField(
            model_name='recurringappointment',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_recurring_appointments', to='accounts.therapistinformation'),
        ),
    ]
