# Generated by Django 5.1.2 on 2025-02-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_guardianinformation_relationship_to_patient'),
        ('appointments', '0008_alter_appointment_therapist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='therapist',
            field=models.ForeignKey(limit_choices_to={'account_id__groups__name': 'Therapist'}, on_delete=django.db.models.deletion.CASCADE, related_name='therapist_appointments', to='accounts.therapistinformation'),
        ),
    ]
