# Generated by Django 5.1.1 on 2025-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='relationship_to_guardian',
            field=models.CharField(default='relationship', max_length=50),
            preserve_default=False,
        ),
    ]





