# Generated by Django 5.1.1 on 2024-10-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientinformation',
            options={'verbose_name': 'Patient Information', 'verbose_name_plural': 'Patients Information'},
        ),
    ]
