# Generated by Django 5.1.1 on 2025-02-09 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('patients', '0002_patientinformation_relationship_to_guardian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='city',
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_residents', to='accounts.municipality'),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_residents', to='accounts.province'),
        ),
    ]
