# Generated by Django 5.1.1 on 2024-10-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientinformation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientinformation',
            old_name='state',
            new_name='province',
        ),
    ]
