# Generated by Django 5.1.1 on 2025-02-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patientinformation_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='contact_number',
        ),
    ]
