# Generated by Django 5.1.1 on 2024-10-16 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_state_patientinformation_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnotes',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='patients.patientinformation'),
        ),
    ]
