# Generated by Django 5.1.2 on 2024-10-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_rename_state_patientinformation_province"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="patientnotes",
            options={
                "verbose_name": "Patient Notes",
                "verbose_name_plural": "Patients Notes",
            },
        ),
        migrations.AlterField(
            model_name="patientnotes",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="patients.patientinformation",
            ),
        ),
        migrations.CreateModel(
            name="Guardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="patientinformation",
            name="guardian",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patients",
                to="patients.guardian",
            ),
        ),
        migrations.AddIndex(
            model_name="patientinformation",
            index=models.Index(
                fields=["account_id"], name="patients_pa_account_952e0c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patientinformation",
            index=models.Index(
                fields=["guardian"], name="patients_pa_guardia_f4826a_idx"
            ),
        ),
    ]
