# Generated by Django 5.1.1 on 2025-01-08 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientnotes_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientinformation',
            options={'verbose_name': 'Patient Information', 'verbose_name_plural': 'Patient Information'},
        ),
        migrations.AlterModelOptions(
            name='patientnotes',
            options={'verbose_name': 'Patient Notes', 'verbose_name_plural': 'Patient Notes'},
        ),
        migrations.RemoveIndex(
            model_name='patientinformation',
            name='patients_pa_account_952e0c_idx',
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientinformation',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_information', to='patients.guardian'),
        ),
    ]
