# Generated by Django 5.1.2 on 2025-01-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patientnotes_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientinformation',
            options={'verbose_name': 'Patient Information', 'verbose_name_plural': 'Patient Information'},
        ),
        migrations.AlterModelOptions(
            name='patientnotes',
            options={'verbose_name': 'Patient Notes', 'verbose_name_plural': 'Patient Notes'},
        ),
    ]
