# Generated by Django 5.1.1 on 2025-01-10 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patientinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='contact_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+639123456789' or '09123456789'.", regex='^(\\+63|0)9\\d{9}$')]),
        ),
    ]
