# Generated by Django 5.1.1 on 2025-01-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patientinformation_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientinformation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
