# Generated by Django 5.1.1 on 2025-01-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patientinformation_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_information', to='patients.guardian'),
        ),
    ]
