# Generated by Django 5.1.2 on 2025-02-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0002_remove_therapist_schedule_availableday'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availableday',
            unique_together={('therapist', 'day', 'start_time', 'end_time')},
        ),
    ]
