# Generated by Django 5.1.2 on 2025-02-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_guardianinformation_relationship_to_patient'),
        ('therapists', '0004_availableslot_delete_availableday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslot',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='accounts.therapistinformation'),
        ),
        migrations.DeleteModel(
            name='Therapist',
        ),
    ]
